version: '3.6'

services:
  web2in1:
    image: glemer/wt_web2in1
    container_name: web2in1
    ports:
    - "80:80/tcp"
    - "443:443/tcp"
    links:
      - "db:database"


  db:
    image: glemer/wt_db
    restart: always

    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user1234'
      MYSQL_ROOT_PASSWORD: 'user1234'

    ports:
      - '3306:3306'

    expose:
      - '3306'

    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d

  volumes:
    mysql-data:
      name: mysql-data