version: '2'


#  Configuration du service docker  

services:

  soa-ext:
    build: 
      context: ./serv_dns/DNS
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dmz_net:
          ipv4_address: 172.16.0.1
    volumes:
      - ./serv_dns/DNS/bind/named.conf
      - ./serv_dns/DNS/bind/db.wt2-9.ephec-ti.be
    container_name: DNS
  
  mail:
    build: 
      dockerfile: Dockerfile
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    networks:
      dmz_net:
 #         ipv4_address: 172.16.1..
    volumes:
    - logs/maildata:/var/mail
    - logs/mailstate:/var/mail-state
    - logs/maillogs:/var/log/mail
    - config/:/tmp/mailServer/
    env_file:
    - .env
    - env-mailServer
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    hostname: mail
    domainname: wt2-9.ephec-ti.be
    container_name: mail

    



# Configuration du réseau docker

networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/24
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.1.0/24
              gateway: 172.16.1.1
  