version: '3.6'

services :
  DNS:
    image: glemer/wt_dns
    restart: always
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/named.conf.options:/etc/bind/named.conf.options
      - ./bind/named.conf.default-zones:/etc/bind/named.conf.default-zones
      - ./bind/named.conf.local:/etc/bind/named.conf.local
      - ./bind/db.wt2-9.ephec-ti.be:/etc/bind/db.wt2-9.ephec-ti.be
      - ./bind/db.internal.wt2-9.ephec-ti.be:/etc/bind/db.wt2-9.ephec-ti.internal.be
    networks:
      DMZ:
        ipv4_address: 172.16.0.2

  web2in1:
    image: glemer/wt_web2in1
    restart: always
    container_name: web2in1
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./app/vitrine/app.conf ${APACHE_CONF_DIR}/sites-enabled/app.conf
      - ./app/b2b/php.ini  ${PHP_CONF_DIR}/apache2/conf.d/custom.ini
    networks:
      web-db-net:
        ipv4_address: 172.16.99.2
      DMZ:
        ipv4_address: 172.16.0.3

  db:
    image: glemer/wt_db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user1234'
      MYSQL_ROOT_PASSWORD: 'user1234'
    ports:
      - '3306:3306/tcp'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d
    networks:
      web-db-net:
        ipv4_address: 172.16.99.3

volumes:
  mysql-data:
    name: mysql-data

networks:
  DMZ:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  web-db-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24
