version: '3.6'

services :
  DNS:
    image: glemer/wt_dns:latest
    restart: always
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/named.conf.options:/etc/bind/named.conf.options
      - ./bind/named.conf.default-zones:/etc/bind/named.conf.default-zones
      - ./bind/named.conf.local:/etc/bind/named.conf.local
      - ./bind/db.wt2-9.ephec-ti.be:/etc/bind/db.wt2-9.ephec-ti.be
      - ./bind/db.internal.wt2-9.ephec-ti.be:/etc/bind/db.wt2-9.ephec-ti.internal.be
      #- ./bind/named.conf.log:/etc/bind/named.conf.log
    networks:
      DMZ:
        ipv4_address: 172.16.0.2

  web2in1:
    image: glemer/wt_web2in1:latest
    restart: always
    container_name: web2in1
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./app/b2b/:/var/www/app/b2b
      - ./app/vitrine/:/var/www/app/vitrine
      - ./app/internal/:/var/www/app/internal
    networks:
      web-db-net:
        ipv4_address: 172.16.99.2
      DMZ:
        ipv4_address: 172.16.0.3

  db:
    image: glemer/wt_db:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_NATIVE_PASSWORD: 'user1234'
      MYSQL_PASSWORD: 'user1234'
      MYSQL_ROOT_PASSWORD: 'user1234'
    ports:
      - '3306:3306/tcp'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d
    networks:
      web-db-net:
        ipv4_address: 172.16.99.3

  voip:
    image: glemer/wt_voip:latest
    container_name: voip
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "15000-15010/udp"
    volumes:
      - ./voip/conf/extensions.conf:/etc/asterisk/extensions.conf
      - ./voip/conf/logger.conf:/etc/asterisk/logger.conf
      - ./voip/conf/sip.conf:/etc/asterisk/sip.conf
      - ./voip/conf/users.conf:/etc/asterisk/users.conf
      - ./voip/conf/voicemail.conf:/etc/asterisk/voicemail.conf
      - ./voip/conf/iax.conf:/etc/asterisk/iax.conf
      - ./voip/conf/queues.conf:/etc/asterisk/queues.conf
      - ./voip/conf/manager.conf:/etc/asterisk/manager.conf
      - ./voip/conf/features.conf:/etc/asterisk/features.conf
    networks:
      DMZ:
        ipv4_address: 172.16.0.5

volumes:
  mysql-data:
    name: mysql-data

networks:
  DMZ:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  web-db-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24
