version: '3.6'

services :
  DNS:
    image: glemer/wt_dns
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/named.conf.options:/etc/bind/named.conf.options
      - ./bind/named.conf.default-zones:/etc/bind/named.conf.default-zones
      - ./bind/named.conf.local:/etc/bind/named.conf.local
      - ./bind/db.wt2-9.ephec-ti.be:/etc/bind/db.wt2-9.ephec-ti.be
      - ./bind/db.internal.wt2-9.ephec-ti.be:/etc/bind/db.wt2-9.ephec-ti.internal.be
    networks:
      DMZ:
        - ipv4_address: 172.16.0.1

  Vitrine:
    image: httpd:2.4
    container_name: vitrine
    ports:
      - "80:80/tcp"
    expose:
      - '80'
    volumes:
      - ./public_html/:/usr/local/apache2/htdocs/
    networks:
      DMZ:
        - ipv4_address: 172.16.0.3

networks:
  DMZ:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
