version: '3.3'

services:
  db:
    image: glemer/wt_db
    restart: always

    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'user1234'

    ports:
      - '3306:3306'

    expose:
      - '3306'

    volumes:
    - mysql-data:/var/lib/mysql
    - ./sql-scripts/:/docker-entrypoint-initdb.d