version : '3.6'

services :
  Directeur:
    image: ubuntu:latest
    container_name: Directeur
    networks:
      Direction:
        ipv4_address: 172.16.1.2

  Secretaire:
    image: ubuntu:latest
    container_name: Secretaire
    networks:
      Direction:
        ipv4_address: 172.16.1.101

  comptableA:
    image: ubuntu:latest
    container_name: comptableA
    networks:
      Administration:
        ipv4_address: 172.16.2.2

  comptableB:
    image: ubuntu:latest
    container_name: comptableB
    networks:
      Administration:
        ipv4_address: 172.16.2.3

  CommercialA:
    image: ubuntu:latest
    container_name: CommercialA
    networks:
      Administration:
        ipv4_address: 172.16.2.101

  CommercialB:
    image: ubuntu:latest
    container_name: CommercialB
    networks:
      Administration:
        ipv4_address: 172.16.2.102

  AtelierA:
    image: ubuntu:latest
    container_name: AtelierA
    networks:
      Atelier:
        ipv4_address: 172.16.3.2

  AtelierB:
    image: ubuntu:latest
    container_name: AtelierB
    networks:
      Atelier:
        ipv4_address: 172.16.3.3

networks:
  Direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
  Administration:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
  Atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
