version : '3.6'

services :
  Directeur:
    image: arnaudnilens/machineinterne:latest
    container_name: Directeur
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Direction:
        ipv4_address: 172.16.1.2

  Secretaire:
    image: arnaudnilens/machineinterne:latest
    container_name: Secretaire
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Direction:
        ipv4_address: 172.16.1.101

  comptableA:
    image: arnaudnilens/machineinterne:latest
    container_name: comptableA
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.2

  comptableB:
    image: arnaudnilens/machineinterne:latest
    container_name: comptableB
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.3

  CommercialA:
    image: arnaudnilens/machineinterne:latest
    container_name: CommercialA
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.101

  CommercialB:
    image: arnaudnilens/machineinterne:latest
    container_name: CommercialB
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.102

  AtelierA:
    image: arnaudnilens/machineinterne:latest
    container_name: AtelierA
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Atelier:
        ipv4_address: 172.16.3.2

  AtelierB:
    image: arnaudnilens/machineinterne:latest
    container_name: AtelierB
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    stdin_open: true
    entrypoint: /bin/bash
    restart: always
    networks:
      Atelier:
        ipv4_address: 172.16.3.3

networks:
  Direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
  Administration:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
  Atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
