version : '3.6'

services :
  Directeur:
    image: ubuntu:latest
    container_name: Directeur
    stdin_open: true
      tty: true
      restart: always
    networks:
      Direction:
        ipv4_address: 172.16.1.2

  Secretaire:
    image: ubuntu:latest
    container_name: Secretaire
    stdin_open: true
      tty: true
      restart: always
    networks:
      Direction:
        ipv4_address: 172.16.1.101

  comptableA:
    image: ubuntu:latest
    container_name: comptableA
    stdin_open: true
      tty: true
      restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.2

  comptableB:
    image: ubuntu:latest
    container_name: comptableB
    stdin_open: true
      tty: true
      restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.3

  CommercialA:
    image: ubuntu:latest
    container_name: CommercialA
    stdin_open: true
      tty: true
      restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.101

  CommercialB:
    image: ubuntu:latest
    container_name: CommercialB
    stdin_open: true
      tty: true
      restart: always
    networks:
      Administration:
        ipv4_address: 172.16.2.102

  AtelierA:
    image: ubuntu:latest
    container_name: AtelierA
    stdin_open: true
      tty: true
      restart: always
    networks:
      Atelier:
        ipv4_address: 172.16.3.2

  AtelierB:
    image: ubuntu:latest
    container_name: AtelierB
    stdin_open: true
      tty: true
      restart: always
    networks:
      Atelier:
        ipv4_address: 172.16.3.3

networks:
  Direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
  Administration:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
  Atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
