version : '2'

services :
  db:
    image: glemer/wt_db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user1234'
      MYSQL_ROOT_PASSWORD: 'user1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d
    networks:
      db_net:
        - ipv4_address: 172.16.99.1


  Directeur:
    image: ubuntu:latest
    container_name: Directeur
    networks:
      Direction:
        ipv4_address: 172.16.1.1

  Secretaire:
    image: ubuntu:latest
    container_name: Secretaire
    networks:
      Direction:
        ipv4_address: 172.16.1.100

  Administration:
    image: ubuntu:latest
    container_name: Administration
    networks:
      Administration:
        ipv4_address: 172.16.2.1

  Marketing:
    image: ubuntu:latest
    container_name: Marketing
    networks:
      Administration:
        ipv4_address: 172.16.2.100

  Atelier:
    image: ubuntu:latest
    container_name: Atelier
    networks:
      Atelier:
        ipv4_address: 172.19.3.1

volumes:
  mysql-data:
    name: mysql-data

networks:
  Direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
  Administration:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
  Atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
  db_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24